# Generated by Django 4.2.4 on 2023-08-07 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('eu', models.CharField(max_length=10)),
                ('timezone', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('coords', models.CharField(max_length=255)),
                ('metro', models.IntegerField()),
                ('area', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='collector.location')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_at', models.DateTimeField()),
                ('metadata', models.JSONField()),
                ('attempt_type', models.CharField(max_length=100)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='collector.ipaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('last_online_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to='collector.ipaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
