# Generated by Django 4.2.4 on 2023-08-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='attempt_type',
            new_name='incident_type',
        ),
    ]
