# Generated by Django 4.2.4 on 2023-08-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_rename_attempt_type_incident_incident_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='country',
            new_name='country_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='area',
        ),
        migrations.RemoveField(
            model_name='location',
            name='eu',
        ),
        migrations.RemoveField(
            model_name='location',
            name='metro',
        ),
        migrations.RemoveField(
            model_name='location',
            name='range',
        ),
        migrations.AddField(
            model_name='location',
            name='accuracy_radius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='autonomous_system_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='autonomous_system_organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='city_confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='continent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='country_confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='country_iso_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_anonymous',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_anonymous_proxy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_anonymous_vpn',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_hosting_provider',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_in_european_union',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='is_legitimate_proxy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_public_proxy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_residential_proxy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_satellite_provider',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_tor_exit_node',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='isp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
