# Generated by Django 4.2.4 on 2023-08-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_rename_country_location_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_in_european_union',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
