# Generated by Django 4.2.4 on 2023-08-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_alter_location_is_in_european_union'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='collector.collector'),
            preserve_default=False,
        ),
    ]
