# Generated by Django 4.2.4 on 2023-08-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_incident_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='token',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
