# Generated by Django 4.2.4 on 2023-08-11 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_alter_collector_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='collector.ipaddress'),
        ),
    ]
