# Generated by Django 4.2.4 on 2023-09-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
