# Generated by Django 4.2.4 on 2023-09-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_notification_incident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
    ]
