# Generated by Django 4.2.4 on 2023-09-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_remove_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('single', 'Single'), ('batch', 'Batch')], default='single', max_length=6),
        ),
        migrations.CreateModel(
            name='IncidentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.incident')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.notification')),
            ],
            options={
                'unique_together': {('incident', 'notification')},
            },
        ),
    ]
